=begin
#fincode API

#fincodeのAPIリファレンスです。\\ fincodeは決済情報のほか様々なリソースを管理できるため、リソース指向なREST APIをベースとしたインターフェイス設計のもとでAPIを提供しています。\\ APIの呼び出しにはAPIキーによる認証が必要であり、リクエストの際に`Authorization`ヘッダーに有効なAPIキーをセットすることで認証できます。 

The version of the OpenAPI document: 1.4.0

Generated by: https://openapi-generator.tech
Generator version: 7.9.0

=end

require 'date'
require 'time'

module FincodeApiClient
  class CardPayTimes
    N3 = "3".freeze
    N5 = "5".freeze
    N6 = "6".freeze
    N10 = "10".freeze
    N12 = "12".freeze
    N15 = "15".freeze
    N18 = "18".freeze
    N20 = "20".freeze
    N24 = "24".freeze

    def self.all_vars
      @all_vars ||= [N3, N5, N6, N10, N12, N15, N18, N20, N24].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if CardPayTimes.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #CardPayTimes"
    end
  end
end
