=begin
#fincode API

#fincodeのAPIリファレンスです。\\ fincodeは決済情報のほか様々なリソースを管理できるため、リソース指向なREST APIをベースとしたインターフェイス設計のもとでAPIを提供しています。\\ APIの呼び出しにはAPIキーによる認証が必要であり、リクエストの際に`Authorization`ヘッダーに有効なAPIキーをセットすることで認証できます。 

The version of the OpenAPI document: 1.4.0

Generated by: https://openapi-generator.tech
Generator version: 7.9.0

=end

require 'date'
require 'time'

module FincodeApiClient
  class CardDestination
    # カードマスタID 
    attr_accessor :contract_card_info_master_id

    # 審査種別マスタID   - `1`：  カード決済（VISA / Mastercard, UCカード社） - `2`：  カード決済（JCB / American Express / Diners Club / Discover） - `3`：  カード決済（VISA / Mastercard, トヨタファイナンス社） 
    attr_accessor :examination_master_id

    # 仕向け先 
    attr_accessor :destination

    # 仕向け先種別 
    attr_accessor :destination_type

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'contract_card_info_master_id' => :'contract_card_info_master_id',
        :'examination_master_id' => :'examination_master_id',
        :'destination' => :'destination',
        :'destination_type' => :'destination_type'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'contract_card_info_master_id' => :'Integer',
        :'examination_master_id' => :'Float',
        :'destination' => :'String',
        :'destination_type' => :'Float'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'contract_card_info_master_id',
        :'examination_master_id',
        :'destination',
        :'destination_type'
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `FincodeApiClient::CardDestination` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `FincodeApiClient::CardDestination`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'contract_card_info_master_id')
        self.contract_card_info_master_id = attributes[:'contract_card_info_master_id']
      end

      if attributes.key?(:'examination_master_id')
        self.examination_master_id = attributes[:'examination_master_id']
      end

      if attributes.key?(:'destination')
        self.destination = attributes[:'destination']
      end

      if attributes.key?(:'destination_type')
        self.destination_type = attributes[:'destination_type']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if !@destination.nil? && @destination.to_s.length > 13
        invalid_properties.push('invalid value for "destination", the character length must be smaller than or equal to 13.')
      end

      if !@destination.nil? && @destination.to_s.length < 1
        invalid_properties.push('invalid value for "destination", the character length must be great than or equal to 1.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      examination_master_id_validator = EnumAttributeValidator.new('Float', [1, 2, 3])
      return false unless examination_master_id_validator.valid?(@examination_master_id)
      return false if !@destination.nil? && @destination.to_s.length > 13
      return false if !@destination.nil? && @destination.to_s.length < 1
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] contract_card_info_master_id Value to be assigned
    def contract_card_info_master_id=(contract_card_info_master_id)
      @contract_card_info_master_id = contract_card_info_master_id
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] examination_master_id Object to be assigned
    def examination_master_id=(examination_master_id)
      validator = EnumAttributeValidator.new('Float', [1, 2, 3])
      unless validator.valid?(examination_master_id)
        fail ArgumentError, "invalid value for \"examination_master_id\", must be one of #{validator.allowable_values}."
      end
      @examination_master_id = examination_master_id
    end

    # Custom attribute writer method with validation
    # @param [Object] destination Value to be assigned
    def destination=(destination)
      if !destination.nil? && destination.to_s.length > 13
        fail ArgumentError, 'invalid value for "destination", the character length must be smaller than or equal to 13.'
      end

      if !destination.nil? && destination.to_s.length < 1
        fail ArgumentError, 'invalid value for "destination", the character length must be great than or equal to 1.'
      end

      @destination = destination
    end

    # Custom attribute writer method with validation
    # @param [Object] destination_type Value to be assigned
    def destination_type=(destination_type)
      @destination_type = destination_type
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          contract_card_info_master_id == o.contract_card_info_master_id &&
          examination_master_id == o.examination_master_id &&
          destination == o.destination &&
          destination_type == o.destination_type
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [contract_card_info_master_id, examination_master_id, destination, destination_type].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def self._deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = FincodeApiClient.const_get(type)
        klass.respond_to?(:openapi_any_of) || klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
