=begin
#fincode API

#fincodeのAPIリファレンスです。\\ fincodeは決済情報のほか様々なリソースを管理できるため、リソース指向なREST APIをベースとしたインターフェイス設計のもとでAPIを提供しています。\\ APIの呼び出しにはAPIキーによる認証が必要であり、リクエストの際に`Authorization`ヘッダーに有効なAPIキーをセットすることで認証できます。 

The version of the OpenAPI document: 1.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.6.0

=end

require 'date'
require 'time'

module FincodeApiClient
  class DepositStatusCode
    N3001 = 3001.freeze
    N3002 = 3002.freeze
    N3003 = 3003.freeze
    N3004 = 3004.freeze
    N3005 = 3005.freeze
    N3006 = 3006.freeze
    N3007 = 3007.freeze
    N3008 = 3008.freeze
    N3009 = 3009.freeze
    N3010 = 3010.freeze
    N3011 = 3011.freeze
    N3012 = 3012.freeze
    N3013 = 3013.freeze

    def self.all_vars
      @all_vars ||= [N3001, N3002, N3003, N3004, N3005, N3006, N3007, N3008, N3009, N3010, N3011, N3012, N3013].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if DepositStatusCode.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #DepositStatusCode"
    end
  end
end
