=begin
#fincode API

#fincodeのAPIリファレンスです。\\ fincodeは決済情報のほか様々なリソースを管理できるため、リソース指向なREST APIをベースとしたインターフェイス設計のもとでAPIを提供しています。\\ APIの呼び出しにはAPIキーによる認証が必要であり、リクエストの際に`Authorization`ヘッダーに有効なAPIキーをセットすることで認証できます。 

The version of the OpenAPI document: 1.4.0

Generated by: https://openapi-generator.tech
Generator version: 7.9.0

=end

require 'date'
require 'time'

module FincodeApiClient
  class ExaminationFileType
    DRIVER_LICENSE_FRONT = "DRIVER_LICENSE_FRONT".freeze
    DRIVER_LICENSE_BACK = "DRIVER_LICENSE_BACK".freeze
    SEAL_REGISTRATION_FRONT = "SEAL_REGISTRATION_FRONT".freeze
    RESIDENT_CARD_FRONT = "RESIDENT_CARD_FRONT".freeze
    RESIDENT_CARD_BACK = "RESIDENT_CARD_BACK".freeze
    SPECIAL_PERMANENT_RESIDENT_FRONT = "SPECIAL_PERMANENT_RESIDENT_FRONT".freeze
    SPECIAL_PERMANENT_RESIDENT_BACK = "SPECIAL_PERMANENT_RESIDENT_BACK".freeze
    CERTIFICATE_OF_RESIDENCE_FRONT = "CERTIFICATE_OF_RESIDENCE_FRONT".freeze
    MY_NUMBER_CARD_FRONT = "MY_NUMBER_CARD_FRONT".freeze
    PRODUCT_IMAGE_1 = "PRODUCT_IMAGE_1".freeze
    PRODUCT_IMAGE_2 = "PRODUCT_IMAGE_2".freeze
    PRODUCT_IMAGE_3 = "PRODUCT_IMAGE_3".freeze
    APP_IMAGE_TOP = "APP_IMAGE_TOP".freeze
    APP_IMAGE_ICON = "APP_IMAGE_ICON".freeze
    SALES_LICENSE_1 = "SALES_LICENSE_1".freeze
    SALES_LICENSE_2 = "SALES_LICENSE_2".freeze
    SALES_LICENSE_3 = "SALES_LICENSE_3".freeze
    COPY_OF_CORPORATE_REGISTRATION = "COPY_OF_CORPORATE_REGISTRATION".freeze

    def self.all_vars
      @all_vars ||= [DRIVER_LICENSE_FRONT, DRIVER_LICENSE_BACK, SEAL_REGISTRATION_FRONT, RESIDENT_CARD_FRONT, RESIDENT_CARD_BACK, SPECIAL_PERMANENT_RESIDENT_FRONT, SPECIAL_PERMANENT_RESIDENT_BACK, CERTIFICATE_OF_RESIDENCE_FRONT, MY_NUMBER_CARD_FRONT, PRODUCT_IMAGE_1, PRODUCT_IMAGE_2, PRODUCT_IMAGE_3, APP_IMAGE_TOP, APP_IMAGE_ICON, SALES_LICENSE_1, SALES_LICENSE_2, SALES_LICENSE_3, COPY_OF_CORPORATE_REGISTRATION].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if ExaminationFileType.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #ExaminationFileType"
    end
  end
end
