=begin
#fincode API

#fincodeのAPIリファレンスです。\\ fincodeは決済情報のほか様々なリソースを管理できるため、リソース指向なREST APIをベースとしたインターフェイス設計のもとでAPIを提供しています。\\ APIの呼び出しにはAPIキーによる認証が必要であり、リクエストの際に`Authorization`ヘッダーに有効なAPIキーをセットすることで認証できます。 

The version of the OpenAPI document: 1.4.0

Generated by: https://openapi-generator.tech
Generator version: 7.9.0

=end

require 'date'
require 'time'

module FincodeApiClient
  class KonbiniCode
    N00010 = "00010".freeze
    N00020 = "00020".freeze
    N00030 = "00030".freeze
    N00080 = "00080".freeze
    N00760 = "00760".freeze

    def self.all_vars
      @all_vars ||= [N00010, N00020, N00030, N00080, N00760].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if KonbiniCode.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #KonbiniCode"
    end
  end
end
