=begin
#fincode API

#fincodeのAPIリファレンスです。\\ fincodeは決済情報のほか様々なリソースを管理できるため、リソース指向なREST APIをベースとしたインターフェイス設計のもとでAPIを提供しています。\\ APIの呼び出しにはAPIキーによる認証が必要であり、リクエストの際に`Authorization`ヘッダーに有効なAPIキーをセットすることで認証できます。 

The version of the OpenAPI document: 1.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.6.0

=end

require 'date'
require 'time'

module FincodeApiClient
  class PaymentPayPay
    # 決済種別\\ この決済で利用する決済手段です。  - `Paypay`: PayPay 
    attr_accessor :pay_type

    attr_accessor :job_code

    # 決済ステータス  - `UNPROCESSED`: 未処理<br /><span class=\"smallText\">請求はまだ実行されていません。</span> - `AWAITING_CUSTOMER_PAYMENT`: 購入者の支払い待ち<br /><span class=\"smallText\">購入者によるPayPay上での取引承認を待っている状態。</span> - `AUTHORIZED`: 仮売上<br /><span class=\"smallText\">仮売上としてPayPay残高の確保が完了しており、売上確定により請求を完了できます。</span> - `CAPTURED`: 売上確定<br /><span class=\"smallText\">請求が完了し、売上が確定しています。</span> - `CANCELED`: キャンセル<br /><span class=\"smallText\">この決済はキャンセルされました。</span> - `EXPIRED`: 決済の期限切れ<br /><span class=\"smallText\">この決済は期限が切れています。</span> 
    attr_accessor :status

    # PayPay支払いURL\\ 購入者をこのURLにリダイレクトすることでPayPay上での取引を開始します。 
    attr_accessor :code_url

    # 支払期限\\ 形式： `yyyy/MM/dd HH:mm:ss.SSS` 
    attr_accessor :code_expiry_date

    # リダイレクトURL\\ 決済が完了した際にPayPayからリダイレクト先URL。 
    attr_accessor :redirect_url

    # リダイレクト先種別\\ `redirect_url`の種別  - `1`： Webページ／Webアプリケーション - `2`： ネイティブアプリ 
    attr_accessor :redirect_type

    # 仮売上期限\\ 形式： `yyyy/MM/dd` 
    attr_accessor :auth_max_date

    # 注文内容の説明\\ 購入者のPayPayアプリ上で表示される注文内容の説明。 
    attr_accessor :order_description

    # 売上確定の説明\\ 購入者のPayPayアプリ上で表示される売上確定の説明。 
    attr_accessor :capture_description

    # 金額変更の説明\\ 購入者のPayPayアプリ上で表示される金額変更の説明。 
    attr_accessor :update_description

    # キャンセルの説明\\ 購入者のPayPayアプリ上で表示されるキャンセルの説明。 
    attr_accessor :cancel_description

    # 店舗ID\\ PayPayによって発行された店舗ID。 
    attr_accessor :store_id

    # PayPayの支払いコードID 
    attr_accessor :code_id

    # PayPay 決済ID 
    attr_accessor :payment_id

    # PayPay処理結果コード 
    attr_accessor :paypay_result_code

    # PayPay トランザクションID 
    attr_accessor :merchant_payment_id

    # PayPay 売上確定ID 
    attr_accessor :merchant_capture_id

    # PayPay 金額変更ID 
    attr_accessor :merchant_update_id

    # PayPay キャンセルID 
    attr_accessor :merchant_revert_id

    # PayPay 返金ID 
    attr_accessor :merchant_refund_id

    # 支払日時\\ 形式： `yyyy/MM/dd HH:mm:ss.SSS` 
    attr_accessor :payment_date

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'pay_type' => :'pay_type',
        :'job_code' => :'job_code',
        :'status' => :'status',
        :'code_url' => :'code_url',
        :'code_expiry_date' => :'code_expiry_date',
        :'redirect_url' => :'redirect_url',
        :'redirect_type' => :'redirect_type',
        :'auth_max_date' => :'auth_max_date',
        :'order_description' => :'order_description',
        :'capture_description' => :'capture_description',
        :'update_description' => :'update_description',
        :'cancel_description' => :'cancel_description',
        :'store_id' => :'store_id',
        :'code_id' => :'code_id',
        :'payment_id' => :'payment_id',
        :'paypay_result_code' => :'paypay_result_code',
        :'merchant_payment_id' => :'merchant_payment_id',
        :'merchant_capture_id' => :'merchant_capture_id',
        :'merchant_update_id' => :'merchant_update_id',
        :'merchant_revert_id' => :'merchant_revert_id',
        :'merchant_refund_id' => :'merchant_refund_id',
        :'payment_date' => :'payment_date'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'pay_type' => :'PayType',
        :'job_code' => :'PayPayPaymentJobCode',
        :'status' => :'PaymentStatus',
        :'code_url' => :'String',
        :'code_expiry_date' => :'String',
        :'redirect_url' => :'String',
        :'redirect_type' => :'String',
        :'auth_max_date' => :'String',
        :'order_description' => :'String',
        :'capture_description' => :'String',
        :'update_description' => :'String',
        :'cancel_description' => :'String',
        :'store_id' => :'String',
        :'code_id' => :'String',
        :'payment_id' => :'String',
        :'paypay_result_code' => :'String',
        :'merchant_payment_id' => :'String',
        :'merchant_capture_id' => :'String',
        :'merchant_update_id' => :'String',
        :'merchant_revert_id' => :'String',
        :'merchant_refund_id' => :'String',
        :'payment_date' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'code_url',
        :'code_expiry_date',
        :'redirect_url',
        :'redirect_type',
        :'auth_max_date',
        :'order_description',
        :'capture_description',
        :'update_description',
        :'cancel_description',
        :'store_id',
        :'code_id',
        :'payment_id',
        :'paypay_result_code',
        :'merchant_payment_id',
        :'merchant_capture_id',
        :'merchant_update_id',
        :'merchant_revert_id',
        :'merchant_refund_id',
        :'payment_date'
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `FincodeApiClient::PaymentPayPay` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `FincodeApiClient::PaymentPayPay`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'pay_type')
        self.pay_type = attributes[:'pay_type']
      end

      if attributes.key?(:'job_code')
        self.job_code = attributes[:'job_code']
      end

      if attributes.key?(:'status')
        self.status = attributes[:'status']
      end

      if attributes.key?(:'code_url')
        self.code_url = attributes[:'code_url']
      end

      if attributes.key?(:'code_expiry_date')
        self.code_expiry_date = attributes[:'code_expiry_date']
      end

      if attributes.key?(:'redirect_url')
        self.redirect_url = attributes[:'redirect_url']
      end

      if attributes.key?(:'redirect_type')
        self.redirect_type = attributes[:'redirect_type']
      end

      if attributes.key?(:'auth_max_date')
        self.auth_max_date = attributes[:'auth_max_date']
      end

      if attributes.key?(:'order_description')
        self.order_description = attributes[:'order_description']
      end

      if attributes.key?(:'capture_description')
        self.capture_description = attributes[:'capture_description']
      end

      if attributes.key?(:'update_description')
        self.update_description = attributes[:'update_description']
      end

      if attributes.key?(:'cancel_description')
        self.cancel_description = attributes[:'cancel_description']
      end

      if attributes.key?(:'store_id')
        self.store_id = attributes[:'store_id']
      end

      if attributes.key?(:'code_id')
        self.code_id = attributes[:'code_id']
      end

      if attributes.key?(:'payment_id')
        self.payment_id = attributes[:'payment_id']
      end

      if attributes.key?(:'paypay_result_code')
        self.paypay_result_code = attributes[:'paypay_result_code']
      end

      if attributes.key?(:'merchant_payment_id')
        self.merchant_payment_id = attributes[:'merchant_payment_id']
      end

      if attributes.key?(:'merchant_capture_id')
        self.merchant_capture_id = attributes[:'merchant_capture_id']
      end

      if attributes.key?(:'merchant_update_id')
        self.merchant_update_id = attributes[:'merchant_update_id']
      end

      if attributes.key?(:'merchant_revert_id')
        self.merchant_revert_id = attributes[:'merchant_revert_id']
      end

      if attributes.key?(:'merchant_refund_id')
        self.merchant_refund_id = attributes[:'merchant_refund_id']
      end

      if attributes.key?(:'payment_date')
        self.payment_date = attributes[:'payment_date']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if !@code_url.nil? && @code_url.to_s.length > 256
        invalid_properties.push('invalid value for "code_url", the character length must be smaller than or equal to 256.')
      end

      if !@code_url.nil? && @code_url.to_s.length < 1
        invalid_properties.push('invalid value for "code_url", the character length must be great than or equal to 1.')
      end

      if !@redirect_url.nil? && @redirect_url.to_s.length > 256
        invalid_properties.push('invalid value for "redirect_url", the character length must be smaller than or equal to 256.')
      end

      if !@redirect_url.nil? && @redirect_url.to_s.length < 1
        invalid_properties.push('invalid value for "redirect_url", the character length must be great than or equal to 1.')
      end

      if !@order_description.nil? && @order_description.to_s.length > 100
        invalid_properties.push('invalid value for "order_description", the character length must be smaller than or equal to 100.')
      end

      if !@capture_description.nil? && @capture_description.to_s.length > 100
        invalid_properties.push('invalid value for "capture_description", the character length must be smaller than or equal to 100.')
      end

      if !@update_description.nil? && @update_description.to_s.length > 100
        invalid_properties.push('invalid value for "update_description", the character length must be smaller than or equal to 100.')
      end

      if !@cancel_description.nil? && @cancel_description.to_s.length > 100
        invalid_properties.push('invalid value for "cancel_description", the character length must be smaller than or equal to 100.')
      end

      if !@store_id.nil? && @store_id.to_s.length > 18
        invalid_properties.push('invalid value for "store_id", the character length must be smaller than or equal to 18.')
      end

      if !@store_id.nil? && @store_id.to_s.length < 1
        invalid_properties.push('invalid value for "store_id", the character length must be great than or equal to 1.')
      end

      if !@code_id.nil? && @code_id.to_s.length > 64
        invalid_properties.push('invalid value for "code_id", the character length must be smaller than or equal to 64.')
      end

      if !@code_id.nil? && @code_id.to_s.length < 1
        invalid_properties.push('invalid value for "code_id", the character length must be great than or equal to 1.')
      end

      if !@payment_id.nil? && @payment_id.to_s.length > 64
        invalid_properties.push('invalid value for "payment_id", the character length must be smaller than or equal to 64.')
      end

      if !@payment_id.nil? && @payment_id.to_s.length < 1
        invalid_properties.push('invalid value for "payment_id", the character length must be great than or equal to 1.')
      end

      if !@paypay_result_code.nil? && @paypay_result_code.to_s.length > 256
        invalid_properties.push('invalid value for "paypay_result_code", the character length must be smaller than or equal to 256.')
      end

      if !@paypay_result_code.nil? && @paypay_result_code.to_s.length < 1
        invalid_properties.push('invalid value for "paypay_result_code", the character length must be great than or equal to 1.')
      end

      if !@merchant_payment_id.nil? && @merchant_payment_id.to_s.length > 64
        invalid_properties.push('invalid value for "merchant_payment_id", the character length must be smaller than or equal to 64.')
      end

      if !@merchant_payment_id.nil? && @merchant_payment_id.to_s.length < 1
        invalid_properties.push('invalid value for "merchant_payment_id", the character length must be great than or equal to 1.')
      end

      if !@merchant_capture_id.nil? && @merchant_capture_id.to_s.length > 64
        invalid_properties.push('invalid value for "merchant_capture_id", the character length must be smaller than or equal to 64.')
      end

      if !@merchant_capture_id.nil? && @merchant_capture_id.to_s.length < 1
        invalid_properties.push('invalid value for "merchant_capture_id", the character length must be great than or equal to 1.')
      end

      if !@merchant_update_id.nil? && @merchant_update_id.to_s.length > 64
        invalid_properties.push('invalid value for "merchant_update_id", the character length must be smaller than or equal to 64.')
      end

      if !@merchant_update_id.nil? && @merchant_update_id.to_s.length < 1
        invalid_properties.push('invalid value for "merchant_update_id", the character length must be great than or equal to 1.')
      end

      if !@merchant_revert_id.nil? && @merchant_revert_id.to_s.length > 64
        invalid_properties.push('invalid value for "merchant_revert_id", the character length must be smaller than or equal to 64.')
      end

      if !@merchant_revert_id.nil? && @merchant_revert_id.to_s.length < 1
        invalid_properties.push('invalid value for "merchant_revert_id", the character length must be great than or equal to 1.')
      end

      if !@merchant_refund_id.nil? && @merchant_refund_id.to_s.length > 64
        invalid_properties.push('invalid value for "merchant_refund_id", the character length must be smaller than or equal to 64.')
      end

      if !@merchant_refund_id.nil? && @merchant_refund_id.to_s.length < 1
        invalid_properties.push('invalid value for "merchant_refund_id", the character length must be great than or equal to 1.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if !@code_url.nil? && @code_url.to_s.length > 256
      return false if !@code_url.nil? && @code_url.to_s.length < 1
      return false if !@redirect_url.nil? && @redirect_url.to_s.length > 256
      return false if !@redirect_url.nil? && @redirect_url.to_s.length < 1
      redirect_type_validator = EnumAttributeValidator.new('String', ["1", "2"])
      return false unless redirect_type_validator.valid?(@redirect_type)
      return false if !@order_description.nil? && @order_description.to_s.length > 100
      return false if !@capture_description.nil? && @capture_description.to_s.length > 100
      return false if !@update_description.nil? && @update_description.to_s.length > 100
      return false if !@cancel_description.nil? && @cancel_description.to_s.length > 100
      return false if !@store_id.nil? && @store_id.to_s.length > 18
      return false if !@store_id.nil? && @store_id.to_s.length < 1
      return false if !@code_id.nil? && @code_id.to_s.length > 64
      return false if !@code_id.nil? && @code_id.to_s.length < 1
      return false if !@payment_id.nil? && @payment_id.to_s.length > 64
      return false if !@payment_id.nil? && @payment_id.to_s.length < 1
      return false if !@paypay_result_code.nil? && @paypay_result_code.to_s.length > 256
      return false if !@paypay_result_code.nil? && @paypay_result_code.to_s.length < 1
      return false if !@merchant_payment_id.nil? && @merchant_payment_id.to_s.length > 64
      return false if !@merchant_payment_id.nil? && @merchant_payment_id.to_s.length < 1
      return false if !@merchant_capture_id.nil? && @merchant_capture_id.to_s.length > 64
      return false if !@merchant_capture_id.nil? && @merchant_capture_id.to_s.length < 1
      return false if !@merchant_update_id.nil? && @merchant_update_id.to_s.length > 64
      return false if !@merchant_update_id.nil? && @merchant_update_id.to_s.length < 1
      return false if !@merchant_revert_id.nil? && @merchant_revert_id.to_s.length > 64
      return false if !@merchant_revert_id.nil? && @merchant_revert_id.to_s.length < 1
      return false if !@merchant_refund_id.nil? && @merchant_refund_id.to_s.length > 64
      return false if !@merchant_refund_id.nil? && @merchant_refund_id.to_s.length < 1
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] code_url Value to be assigned
    def code_url=(code_url)
      if !code_url.nil? && code_url.to_s.length > 256
        fail ArgumentError, 'invalid value for "code_url", the character length must be smaller than or equal to 256.'
      end

      if !code_url.nil? && code_url.to_s.length < 1
        fail ArgumentError, 'invalid value for "code_url", the character length must be great than or equal to 1.'
      end

      @code_url = code_url
    end

    # Custom attribute writer method with validation
    # @param [Object] redirect_url Value to be assigned
    def redirect_url=(redirect_url)
      if !redirect_url.nil? && redirect_url.to_s.length > 256
        fail ArgumentError, 'invalid value for "redirect_url", the character length must be smaller than or equal to 256.'
      end

      if !redirect_url.nil? && redirect_url.to_s.length < 1
        fail ArgumentError, 'invalid value for "redirect_url", the character length must be great than or equal to 1.'
      end

      @redirect_url = redirect_url
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] redirect_type Object to be assigned
    def redirect_type=(redirect_type)
      validator = EnumAttributeValidator.new('String', ["1", "2"])
      unless validator.valid?(redirect_type)
        fail ArgumentError, "invalid value for \"redirect_type\", must be one of #{validator.allowable_values}."
      end
      @redirect_type = redirect_type
    end

    # Custom attribute writer method with validation
    # @param [Object] order_description Value to be assigned
    def order_description=(order_description)
      if !order_description.nil? && order_description.to_s.length > 100
        fail ArgumentError, 'invalid value for "order_description", the character length must be smaller than or equal to 100.'
      end

      @order_description = order_description
    end

    # Custom attribute writer method with validation
    # @param [Object] capture_description Value to be assigned
    def capture_description=(capture_description)
      if !capture_description.nil? && capture_description.to_s.length > 100
        fail ArgumentError, 'invalid value for "capture_description", the character length must be smaller than or equal to 100.'
      end

      @capture_description = capture_description
    end

    # Custom attribute writer method with validation
    # @param [Object] update_description Value to be assigned
    def update_description=(update_description)
      if !update_description.nil? && update_description.to_s.length > 100
        fail ArgumentError, 'invalid value for "update_description", the character length must be smaller than or equal to 100.'
      end

      @update_description = update_description
    end

    # Custom attribute writer method with validation
    # @param [Object] cancel_description Value to be assigned
    def cancel_description=(cancel_description)
      if !cancel_description.nil? && cancel_description.to_s.length > 100
        fail ArgumentError, 'invalid value for "cancel_description", the character length must be smaller than or equal to 100.'
      end

      @cancel_description = cancel_description
    end

    # Custom attribute writer method with validation
    # @param [Object] store_id Value to be assigned
    def store_id=(store_id)
      if !store_id.nil? && store_id.to_s.length > 18
        fail ArgumentError, 'invalid value for "store_id", the character length must be smaller than or equal to 18.'
      end

      if !store_id.nil? && store_id.to_s.length < 1
        fail ArgumentError, 'invalid value for "store_id", the character length must be great than or equal to 1.'
      end

      @store_id = store_id
    end

    # Custom attribute writer method with validation
    # @param [Object] code_id Value to be assigned
    def code_id=(code_id)
      if !code_id.nil? && code_id.to_s.length > 64
        fail ArgumentError, 'invalid value for "code_id", the character length must be smaller than or equal to 64.'
      end

      if !code_id.nil? && code_id.to_s.length < 1
        fail ArgumentError, 'invalid value for "code_id", the character length must be great than or equal to 1.'
      end

      @code_id = code_id
    end

    # Custom attribute writer method with validation
    # @param [Object] payment_id Value to be assigned
    def payment_id=(payment_id)
      if !payment_id.nil? && payment_id.to_s.length > 64
        fail ArgumentError, 'invalid value for "payment_id", the character length must be smaller than or equal to 64.'
      end

      if !payment_id.nil? && payment_id.to_s.length < 1
        fail ArgumentError, 'invalid value for "payment_id", the character length must be great than or equal to 1.'
      end

      @payment_id = payment_id
    end

    # Custom attribute writer method with validation
    # @param [Object] paypay_result_code Value to be assigned
    def paypay_result_code=(paypay_result_code)
      if !paypay_result_code.nil? && paypay_result_code.to_s.length > 256
        fail ArgumentError, 'invalid value for "paypay_result_code", the character length must be smaller than or equal to 256.'
      end

      if !paypay_result_code.nil? && paypay_result_code.to_s.length < 1
        fail ArgumentError, 'invalid value for "paypay_result_code", the character length must be great than or equal to 1.'
      end

      @paypay_result_code = paypay_result_code
    end

    # Custom attribute writer method with validation
    # @param [Object] merchant_payment_id Value to be assigned
    def merchant_payment_id=(merchant_payment_id)
      if !merchant_payment_id.nil? && merchant_payment_id.to_s.length > 64
        fail ArgumentError, 'invalid value for "merchant_payment_id", the character length must be smaller than or equal to 64.'
      end

      if !merchant_payment_id.nil? && merchant_payment_id.to_s.length < 1
        fail ArgumentError, 'invalid value for "merchant_payment_id", the character length must be great than or equal to 1.'
      end

      @merchant_payment_id = merchant_payment_id
    end

    # Custom attribute writer method with validation
    # @param [Object] merchant_capture_id Value to be assigned
    def merchant_capture_id=(merchant_capture_id)
      if !merchant_capture_id.nil? && merchant_capture_id.to_s.length > 64
        fail ArgumentError, 'invalid value for "merchant_capture_id", the character length must be smaller than or equal to 64.'
      end

      if !merchant_capture_id.nil? && merchant_capture_id.to_s.length < 1
        fail ArgumentError, 'invalid value for "merchant_capture_id", the character length must be great than or equal to 1.'
      end

      @merchant_capture_id = merchant_capture_id
    end

    # Custom attribute writer method with validation
    # @param [Object] merchant_update_id Value to be assigned
    def merchant_update_id=(merchant_update_id)
      if !merchant_update_id.nil? && merchant_update_id.to_s.length > 64
        fail ArgumentError, 'invalid value for "merchant_update_id", the character length must be smaller than or equal to 64.'
      end

      if !merchant_update_id.nil? && merchant_update_id.to_s.length < 1
        fail ArgumentError, 'invalid value for "merchant_update_id", the character length must be great than or equal to 1.'
      end

      @merchant_update_id = merchant_update_id
    end

    # Custom attribute writer method with validation
    # @param [Object] merchant_revert_id Value to be assigned
    def merchant_revert_id=(merchant_revert_id)
      if !merchant_revert_id.nil? && merchant_revert_id.to_s.length > 64
        fail ArgumentError, 'invalid value for "merchant_revert_id", the character length must be smaller than or equal to 64.'
      end

      if !merchant_revert_id.nil? && merchant_revert_id.to_s.length < 1
        fail ArgumentError, 'invalid value for "merchant_revert_id", the character length must be great than or equal to 1.'
      end

      @merchant_revert_id = merchant_revert_id
    end

    # Custom attribute writer method with validation
    # @param [Object] merchant_refund_id Value to be assigned
    def merchant_refund_id=(merchant_refund_id)
      if !merchant_refund_id.nil? && merchant_refund_id.to_s.length > 64
        fail ArgumentError, 'invalid value for "merchant_refund_id", the character length must be smaller than or equal to 64.'
      end

      if !merchant_refund_id.nil? && merchant_refund_id.to_s.length < 1
        fail ArgumentError, 'invalid value for "merchant_refund_id", the character length must be great than or equal to 1.'
      end

      @merchant_refund_id = merchant_refund_id
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          pay_type == o.pay_type &&
          job_code == o.job_code &&
          status == o.status &&
          code_url == o.code_url &&
          code_expiry_date == o.code_expiry_date &&
          redirect_url == o.redirect_url &&
          redirect_type == o.redirect_type &&
          auth_max_date == o.auth_max_date &&
          order_description == o.order_description &&
          capture_description == o.capture_description &&
          update_description == o.update_description &&
          cancel_description == o.cancel_description &&
          store_id == o.store_id &&
          code_id == o.code_id &&
          payment_id == o.payment_id &&
          paypay_result_code == o.paypay_result_code &&
          merchant_payment_id == o.merchant_payment_id &&
          merchant_capture_id == o.merchant_capture_id &&
          merchant_update_id == o.merchant_update_id &&
          merchant_revert_id == o.merchant_revert_id &&
          merchant_refund_id == o.merchant_refund_id &&
          payment_date == o.payment_date
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [pay_type, job_code, status, code_url, code_expiry_date, redirect_url, redirect_type, auth_max_date, order_description, capture_description, update_description, cancel_description, store_id, code_id, payment_id, paypay_result_code, merchant_payment_id, merchant_capture_id, merchant_update_id, merchant_revert_id, merchant_refund_id, payment_date].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def self._deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = FincodeApiClient.const_get(type)
        klass.respond_to?(:openapi_any_of) || klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
