=begin
#fincode API

#fincodeのAPIリファレンスです。\\ fincodeは決済情報のほか様々なリソースを管理できるため、リソース指向なREST APIをベースとしたインターフェイス設計のもとでAPIを提供しています。\\ APIの呼び出しにはAPIキーによる認証が必要であり、リクエストの際に`Authorization`ヘッダーに有効なAPIキーをセットすることで認証できます。 

The version of the OpenAPI document: 1.4.0

Generated by: https://openapi-generator.tech
Generator version: 7.19.0

=end

require 'date'
require 'time'

module FincodeApiClient
  class PaymentGooglePayChangingAmountRequest < ApiModelBase
    # 決済種別\\ この決済で利用する決済手段です。  - `Googlepay`: Google Pay 
    attr_accessor :pay_type

    # 取引ID 
    attr_accessor :access_id

    # 利用金額\\ `tax`との合計値が決済手段ごとに定められた決済金額の範囲内に収まる必要があります。\\ 参照： [Google Pay > 制限事項 > 利用可能な金額](/payment/googlepay/restriction) 
    attr_accessor :amount

    # 税送料\\ `amount`との合計値が決済手段ごとに定められた決済金額の範囲内に収まる必要があります。\\ 参照： [Google Pay > 制限事項 > 利用可能な金額](/payment/googlepay/restriction) 
    attr_accessor :tax

    # 取引種別\\ 仮売上にするか即座に売上確定するかを指定します。  - `AUTH`：仮売上 - `CAPTURE`：即時売上 
    attr_accessor :job_code

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'pay_type' => :'pay_type',
        :'access_id' => :'access_id',
        :'amount' => :'amount',
        :'tax' => :'tax',
        :'job_code' => :'job_code'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'pay_type' => :'PayType',
        :'access_id' => :'String',
        :'amount' => :'String',
        :'tax' => :'String',
        :'job_code' => :'CardPaymentJobCode'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'tax',
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `FincodeApiClient::PaymentGooglePayChangingAmountRequest` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `FincodeApiClient::PaymentGooglePayChangingAmountRequest`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'pay_type')
        self.pay_type = attributes[:'pay_type']
      else
        self.pay_type = nil
      end

      if attributes.key?(:'access_id')
        self.access_id = attributes[:'access_id']
      else
        self.access_id = nil
      end

      if attributes.key?(:'amount')
        self.amount = attributes[:'amount']
      else
        self.amount = nil
      end

      if attributes.key?(:'tax')
        self.tax = attributes[:'tax']
      end

      if attributes.key?(:'job_code')
        self.job_code = attributes[:'job_code']
      else
        self.job_code = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @pay_type.nil?
        invalid_properties.push('invalid value for "pay_type", pay_type cannot be nil.')
      end

      if @access_id.nil?
        invalid_properties.push('invalid value for "access_id", access_id cannot be nil.')
      end

      if @access_id.to_s.length > 24
        invalid_properties.push('invalid value for "access_id", the character length must be smaller than or equal to 24.')
      end

      if @access_id.to_s.length < 24
        invalid_properties.push('invalid value for "access_id", the character length must be greater than or equal to 24.')
      end

      if @amount.nil?
        invalid_properties.push('invalid value for "amount", amount cannot be nil.')
      end

      if @amount.to_s.length > 7
        invalid_properties.push('invalid value for "amount", the character length must be smaller than or equal to 7.')
      end

      if @amount.to_s.length < 1
        invalid_properties.push('invalid value for "amount", the character length must be greater than or equal to 1.')
      end

      if !@tax.nil? && @tax.to_s.length > 7
        invalid_properties.push('invalid value for "tax", the character length must be smaller than or equal to 7.')
      end

      if !@tax.nil? && @tax.to_s.length < 1
        invalid_properties.push('invalid value for "tax", the character length must be greater than or equal to 1.')
      end

      if @job_code.nil?
        invalid_properties.push('invalid value for "job_code", job_code cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @pay_type.nil?
      return false if @access_id.nil?
      return false if @access_id.to_s.length > 24
      return false if @access_id.to_s.length < 24
      return false if @amount.nil?
      return false if @amount.to_s.length > 7
      return false if @amount.to_s.length < 1
      return false if !@tax.nil? && @tax.to_s.length > 7
      return false if !@tax.nil? && @tax.to_s.length < 1
      return false if @job_code.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] pay_type Value to be assigned
    def pay_type=(pay_type)
      if pay_type.nil?
        fail ArgumentError, 'pay_type cannot be nil'
      end

      @pay_type = pay_type
    end

    # Custom attribute writer method with validation
    # @param [Object] access_id Value to be assigned
    def access_id=(access_id)
      if access_id.nil?
        fail ArgumentError, 'access_id cannot be nil'
      end

      if access_id.to_s.length > 24
        fail ArgumentError, 'invalid value for "access_id", the character length must be smaller than or equal to 24.'
      end

      if access_id.to_s.length < 24
        fail ArgumentError, 'invalid value for "access_id", the character length must be greater than or equal to 24.'
      end

      @access_id = access_id
    end

    # Custom attribute writer method with validation
    # @param [Object] amount Value to be assigned
    def amount=(amount)
      if amount.nil?
        fail ArgumentError, 'amount cannot be nil'
      end

      if amount.to_s.length > 7
        fail ArgumentError, 'invalid value for "amount", the character length must be smaller than or equal to 7.'
      end

      if amount.to_s.length < 1
        fail ArgumentError, 'invalid value for "amount", the character length must be greater than or equal to 1.'
      end

      @amount = amount
    end

    # Custom attribute writer method with validation
    # @param [Object] tax Value to be assigned
    def tax=(tax)
      if !tax.nil? && tax.to_s.length > 7
        fail ArgumentError, 'invalid value for "tax", the character length must be smaller than or equal to 7.'
      end

      if !tax.nil? && tax.to_s.length < 1
        fail ArgumentError, 'invalid value for "tax", the character length must be greater than or equal to 1.'
      end

      @tax = tax
    end

    # Custom attribute writer method with validation
    # @param [Object] job_code Value to be assigned
    def job_code=(job_code)
      if job_code.nil?
        fail ArgumentError, 'job_code cannot be nil'
      end

      @job_code = job_code
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          pay_type == o.pay_type &&
          access_id == o.access_id &&
          amount == o.amount &&
          tax == o.tax &&
          job_code == o.job_code
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [pay_type, access_id, amount, tax, job_code].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
