=begin
#fincode API

#fincodeのAPIリファレンスです。\\ fincodeは決済情報のほか様々なリソースを管理できるため、リソース指向なREST APIをベースとしたインターフェイス設計のもとでAPIを提供しています。\\ APIの呼び出しにはAPIキーによる認証が必要であり、リクエストの際に`Authorization`ヘッダーに有効なAPIキーをセットすることで認証できます。 

The version of the OpenAPI document: 1.4.0

Generated by: https://openapi-generator.tech
Generator version: 7.19.0

=end

require 'date'
require 'time'

module FincodeApiClient
  class ShopInfoV2PrepaidPointInfo < ApiModelBase
    # ポイント利用方法\\ \\ プリペイドポイントの利用方法 
    attr_accessor :how_to_use

    # ポイント有効期限について\\ \\ プリペイドポイントの有効期限について 
    attr_accessor :about_expiration

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'how_to_use' => :'how_to_use',
        :'about_expiration' => :'about_expiration'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'how_to_use' => :'String',
        :'about_expiration' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'how_to_use',
        :'about_expiration'
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `FincodeApiClient::ShopInfoV2PrepaidPointInfo` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `FincodeApiClient::ShopInfoV2PrepaidPointInfo`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'how_to_use')
        self.how_to_use = attributes[:'how_to_use']
      end

      if attributes.key?(:'about_expiration')
        self.about_expiration = attributes[:'about_expiration']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if !@how_to_use.nil? && @how_to_use.to_s.length > 300
        invalid_properties.push('invalid value for "how_to_use", the character length must be smaller than or equal to 300.')
      end

      if !@how_to_use.nil? && @how_to_use.to_s.length < 1
        invalid_properties.push('invalid value for "how_to_use", the character length must be greater than or equal to 1.')
      end

      if !@about_expiration.nil? && @about_expiration.to_s.length > 300
        invalid_properties.push('invalid value for "about_expiration", the character length must be smaller than or equal to 300.')
      end

      if !@about_expiration.nil? && @about_expiration.to_s.length < 1
        invalid_properties.push('invalid value for "about_expiration", the character length must be greater than or equal to 1.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if !@how_to_use.nil? && @how_to_use.to_s.length > 300
      return false if !@how_to_use.nil? && @how_to_use.to_s.length < 1
      return false if !@about_expiration.nil? && @about_expiration.to_s.length > 300
      return false if !@about_expiration.nil? && @about_expiration.to_s.length < 1
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] how_to_use Value to be assigned
    def how_to_use=(how_to_use)
      if !how_to_use.nil? && how_to_use.to_s.length > 300
        fail ArgumentError, 'invalid value for "how_to_use", the character length must be smaller than or equal to 300.'
      end

      if !how_to_use.nil? && how_to_use.to_s.length < 1
        fail ArgumentError, 'invalid value for "how_to_use", the character length must be greater than or equal to 1.'
      end

      @how_to_use = how_to_use
    end

    # Custom attribute writer method with validation
    # @param [Object] about_expiration Value to be assigned
    def about_expiration=(about_expiration)
      if !about_expiration.nil? && about_expiration.to_s.length > 300
        fail ArgumentError, 'invalid value for "about_expiration", the character length must be smaller than or equal to 300.'
      end

      if !about_expiration.nil? && about_expiration.to_s.length < 1
        fail ArgumentError, 'invalid value for "about_expiration", the character length must be greater than or equal to 1.'
      end

      @about_expiration = about_expiration
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          how_to_use == o.how_to_use &&
          about_expiration == o.about_expiration
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [how_to_use, about_expiration].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
