=begin
#fincode API

#fincodeのAPIリファレンスです。\\ fincodeは決済情報のほか様々なリソースを管理できるため、リソース指向なREST APIをベースとしたインターフェイス設計のもとでAPIを提供しています。\\ APIの呼び出しにはAPIキーによる認証が必要であり、リクエストの際に`Authorization`ヘッダーに有効なAPIキーをセットすることで認証できます。 

The version of the OpenAPI document: 1.4.0

Generated by: https://openapi-generator.tech
Generator version: 7.9.0

=end

require 'date'
require 'time'

module FincodeApiClient
  class Subscription
    # サブスクリプションID 
    attr_accessor :id

    # ショップID 
    attr_accessor :shop_id

    attr_accessor :pay_type

    # プランID 
    attr_accessor :plan_id

    # プラン名 
    attr_accessor :plan_name

    # 顧客ID\\ \\ このサブスクリプションの請求先となる顧客のIDです。 
    attr_accessor :customer_id

    # カードID\\ \\ このサブスクリプションの決済に使用するカードのIDです。 
    attr_accessor :card_id

    # 決済手段ID\\ \\ このサブスクリプションの決済に使用する決済手段のIDです。 
    attr_accessor :payment_method_id

    # 利用金額 
    attr_accessor :amount

    # 税送料 
    attr_accessor :tax

    # 合計金額\\ 利用金額と税送料の合計金額です。 
    attr_accessor :total_amount

    # 初回利用金額\\ \\ この値が設定されているとき、このサブスクリプションは初回の課金のみこの金額で課金し、2回目以降はプラン情報がもつ`amount`の金額で課金します。 
    attr_accessor :initial_amount

    # 初回税送料\\ \\ この値が設定されているとき、このサブスクリプションは初回の課金のみこの金額で課金し、2回目以降はプラン情報がもつ`tax`の金額で課金します。 
    attr_accessor :initial_tax

    # 初回合計金額\\ \\ `initial_amount`と`initial_tax`の合計金額です。 
    attr_accessor :initial_total_amount

    attr_accessor :status

    # 課金開始日\\ サブスクリプションの開始日です。\\ \\ 形式：`yyyy/MM/dd HH:mm:ss.SSS` 
    attr_accessor :start_date

    # 次回課金日\\ サブスクリプションの次回課金日です。\\ \\ 形式：`yyyy/MM/dd HH:mm:ss.SSS` 
    attr_accessor :next_charge_date

    # 課金停止日\\ サブスクリプションの停止日です。\\ \\ 形式：`yyyy/MM/dd HH:mm:ss.SSS` 
    attr_accessor :stop_date

    # 月末課金フラグ  - `0`：月末課金を行わない - `1`：月末課金を行う 
    attr_accessor :end_month_flag

    # ※ 閉塞機能 
    attr_accessor :send_url

    # このサブスクリプションにおいて発生したエラーのうち、一番最新のエラーのエラーコードです。\\ [各エラーコードの定義はこちらを参照](https://docs.fincode.jp/develop_support/error)して確認できます。 
    attr_accessor :error_code

    # 加盟店自由項目 1 
    attr_accessor :client_field_1

    # 加盟店自由項目 2 
    attr_accessor :client_field_2

    # 加盟店自由項目 3 
    attr_accessor :client_field_3

    # ご利用明細表示内容 
    attr_accessor :remarks

    # 作成日\\ 形式：`yyyy/MM/dd HH:mm:ss.SSS` 
    attr_accessor :created

    # 更新日\\ 形式：`yyyy/MM/dd HH:mm:ss.SSS` 
    attr_accessor :updated

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'id' => :'id',
        :'shop_id' => :'shop_id',
        :'pay_type' => :'pay_type',
        :'plan_id' => :'plan_id',
        :'plan_name' => :'plan_name',
        :'customer_id' => :'customer_id',
        :'card_id' => :'card_id',
        :'payment_method_id' => :'payment_method_id',
        :'amount' => :'amount',
        :'tax' => :'tax',
        :'total_amount' => :'total_amount',
        :'initial_amount' => :'initial_amount',
        :'initial_tax' => :'initial_tax',
        :'initial_total_amount' => :'initial_total_amount',
        :'status' => :'status',
        :'start_date' => :'start_date',
        :'next_charge_date' => :'next_charge_date',
        :'stop_date' => :'stop_date',
        :'end_month_flag' => :'end_month_flag',
        :'send_url' => :'send_url',
        :'error_code' => :'error_code',
        :'client_field_1' => :'client_field_1',
        :'client_field_2' => :'client_field_2',
        :'client_field_3' => :'client_field_3',
        :'remarks' => :'remarks',
        :'created' => :'created',
        :'updated' => :'updated'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'id' => :'String',
        :'shop_id' => :'String',
        :'pay_type' => :'SubscriptionPayType',
        :'plan_id' => :'String',
        :'plan_name' => :'String',
        :'customer_id' => :'String',
        :'card_id' => :'String',
        :'payment_method_id' => :'String',
        :'amount' => :'Integer',
        :'tax' => :'Integer',
        :'total_amount' => :'Integer',
        :'initial_amount' => :'Integer',
        :'initial_tax' => :'Integer',
        :'initial_total_amount' => :'Integer',
        :'status' => :'SubscriptionStatus',
        :'start_date' => :'String',
        :'next_charge_date' => :'String',
        :'stop_date' => :'String',
        :'end_month_flag' => :'String',
        :'send_url' => :'String',
        :'error_code' => :'String',
        :'client_field_1' => :'String',
        :'client_field_2' => :'String',
        :'client_field_3' => :'String',
        :'remarks' => :'String',
        :'created' => :'String',
        :'updated' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'plan_name',
        :'stop_date',
        :'send_url',
        :'error_code',
        :'client_field_1',
        :'client_field_2',
        :'client_field_3',
        :'remarks',
        :'updated'
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `FincodeApiClient::Subscription` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `FincodeApiClient::Subscription`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'id')
        self.id = attributes[:'id']
      end

      if attributes.key?(:'shop_id')
        self.shop_id = attributes[:'shop_id']
      end

      if attributes.key?(:'pay_type')
        self.pay_type = attributes[:'pay_type']
      end

      if attributes.key?(:'plan_id')
        self.plan_id = attributes[:'plan_id']
      end

      if attributes.key?(:'plan_name')
        self.plan_name = attributes[:'plan_name']
      end

      if attributes.key?(:'customer_id')
        self.customer_id = attributes[:'customer_id']
      end

      if attributes.key?(:'card_id')
        self.card_id = attributes[:'card_id']
      end

      if attributes.key?(:'payment_method_id')
        self.payment_method_id = attributes[:'payment_method_id']
      end

      if attributes.key?(:'amount')
        self.amount = attributes[:'amount']
      end

      if attributes.key?(:'tax')
        self.tax = attributes[:'tax']
      end

      if attributes.key?(:'total_amount')
        self.total_amount = attributes[:'total_amount']
      end

      if attributes.key?(:'initial_amount')
        self.initial_amount = attributes[:'initial_amount']
      end

      if attributes.key?(:'initial_tax')
        self.initial_tax = attributes[:'initial_tax']
      end

      if attributes.key?(:'initial_total_amount')
        self.initial_total_amount = attributes[:'initial_total_amount']
      end

      if attributes.key?(:'status')
        self.status = attributes[:'status']
      end

      if attributes.key?(:'start_date')
        self.start_date = attributes[:'start_date']
      end

      if attributes.key?(:'next_charge_date')
        self.next_charge_date = attributes[:'next_charge_date']
      end

      if attributes.key?(:'stop_date')
        self.stop_date = attributes[:'stop_date']
      end

      if attributes.key?(:'end_month_flag')
        self.end_month_flag = attributes[:'end_month_flag']
      end

      if attributes.key?(:'send_url')
        self.send_url = attributes[:'send_url']
      end

      if attributes.key?(:'error_code')
        self.error_code = attributes[:'error_code']
      end

      if attributes.key?(:'client_field_1')
        self.client_field_1 = attributes[:'client_field_1']
      end

      if attributes.key?(:'client_field_2')
        self.client_field_2 = attributes[:'client_field_2']
      end

      if attributes.key?(:'client_field_3')
        self.client_field_3 = attributes[:'client_field_3']
      end

      if attributes.key?(:'remarks')
        self.remarks = attributes[:'remarks']
      end

      if attributes.key?(:'created')
        self.created = attributes[:'created']
      end

      if attributes.key?(:'updated')
        self.updated = attributes[:'updated']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if !@id.nil? && @id.to_s.length > 25
        invalid_properties.push('invalid value for "id", the character length must be smaller than or equal to 25.')
      end

      if !@id.nil? && @id.to_s.length < 1
        invalid_properties.push('invalid value for "id", the character length must be great than or equal to 1.')
      end

      if !@shop_id.nil? && @shop_id.to_s.length > 13
        invalid_properties.push('invalid value for "shop_id", the character length must be smaller than or equal to 13.')
      end

      if !@shop_id.nil? && @shop_id.to_s.length < 13
        invalid_properties.push('invalid value for "shop_id", the character length must be great than or equal to 13.')
      end

      if !@plan_id.nil? && @plan_id.to_s.length > 25
        invalid_properties.push('invalid value for "plan_id", the character length must be smaller than or equal to 25.')
      end

      if !@plan_id.nil? && @plan_id.to_s.length < 1
        invalid_properties.push('invalid value for "plan_id", the character length must be great than or equal to 1.')
      end

      if !@plan_name.nil? && @plan_name.to_s.length > 200
        invalid_properties.push('invalid value for "plan_name", the character length must be smaller than or equal to 200.')
      end

      if !@customer_id.nil? && @customer_id.to_s.length > 60
        invalid_properties.push('invalid value for "customer_id", the character length must be smaller than or equal to 60.')
      end

      if !@customer_id.nil? && @customer_id.to_s.length < 1
        invalid_properties.push('invalid value for "customer_id", the character length must be great than or equal to 1.')
      end

      if !@card_id.nil? && @card_id.to_s.length > 25
        invalid_properties.push('invalid value for "card_id", the character length must be smaller than or equal to 25.')
      end

      if !@card_id.nil? && @card_id.to_s.length < 25
        invalid_properties.push('invalid value for "card_id", the character length must be great than or equal to 25.')
      end

      if !@payment_method_id.nil? && @payment_method_id.to_s.length > 25
        invalid_properties.push('invalid value for "payment_method_id", the character length must be smaller than or equal to 25.')
      end

      if !@payment_method_id.nil? && @payment_method_id.to_s.length < 25
        invalid_properties.push('invalid value for "payment_method_id", the character length must be great than or equal to 25.')
      end

      if !@error_code.nil? && @error_code.to_s.length > 11
        invalid_properties.push('invalid value for "error_code", the character length must be smaller than or equal to 11.')
      end

      if !@error_code.nil? && @error_code.to_s.length < 11
        invalid_properties.push('invalid value for "error_code", the character length must be great than or equal to 11.')
      end

      if !@client_field_1.nil? && @client_field_1.to_s.length > 100
        invalid_properties.push('invalid value for "client_field_1", the character length must be smaller than or equal to 100.')
      end

      if !@client_field_1.nil? && @client_field_1.to_s.length < 1
        invalid_properties.push('invalid value for "client_field_1", the character length must be great than or equal to 1.')
      end

      if !@client_field_2.nil? && @client_field_2.to_s.length > 100
        invalid_properties.push('invalid value for "client_field_2", the character length must be smaller than or equal to 100.')
      end

      if !@client_field_2.nil? && @client_field_2.to_s.length < 1
        invalid_properties.push('invalid value for "client_field_2", the character length must be great than or equal to 1.')
      end

      if !@client_field_3.nil? && @client_field_3.to_s.length > 100
        invalid_properties.push('invalid value for "client_field_3", the character length must be smaller than or equal to 100.')
      end

      if !@client_field_3.nil? && @client_field_3.to_s.length < 1
        invalid_properties.push('invalid value for "client_field_3", the character length must be great than or equal to 1.')
      end

      if !@remarks.nil? && @remarks.to_s.length > 9
        invalid_properties.push('invalid value for "remarks", the character length must be smaller than or equal to 9.')
      end

      if !@remarks.nil? && @remarks.to_s.length < 1
        invalid_properties.push('invalid value for "remarks", the character length must be great than or equal to 1.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if !@id.nil? && @id.to_s.length > 25
      return false if !@id.nil? && @id.to_s.length < 1
      return false if !@shop_id.nil? && @shop_id.to_s.length > 13
      return false if !@shop_id.nil? && @shop_id.to_s.length < 13
      return false if !@plan_id.nil? && @plan_id.to_s.length > 25
      return false if !@plan_id.nil? && @plan_id.to_s.length < 1
      return false if !@plan_name.nil? && @plan_name.to_s.length > 200
      return false if !@customer_id.nil? && @customer_id.to_s.length > 60
      return false if !@customer_id.nil? && @customer_id.to_s.length < 1
      return false if !@card_id.nil? && @card_id.to_s.length > 25
      return false if !@card_id.nil? && @card_id.to_s.length < 25
      return false if !@payment_method_id.nil? && @payment_method_id.to_s.length > 25
      return false if !@payment_method_id.nil? && @payment_method_id.to_s.length < 25
      end_month_flag_validator = EnumAttributeValidator.new('String', ["0", "1"])
      return false unless end_month_flag_validator.valid?(@end_month_flag)
      return false if !@error_code.nil? && @error_code.to_s.length > 11
      return false if !@error_code.nil? && @error_code.to_s.length < 11
      return false if !@client_field_1.nil? && @client_field_1.to_s.length > 100
      return false if !@client_field_1.nil? && @client_field_1.to_s.length < 1
      return false if !@client_field_2.nil? && @client_field_2.to_s.length > 100
      return false if !@client_field_2.nil? && @client_field_2.to_s.length < 1
      return false if !@client_field_3.nil? && @client_field_3.to_s.length > 100
      return false if !@client_field_3.nil? && @client_field_3.to_s.length < 1
      return false if !@remarks.nil? && @remarks.to_s.length > 9
      return false if !@remarks.nil? && @remarks.to_s.length < 1
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] id Value to be assigned
    def id=(id)
      if id.nil?
        fail ArgumentError, 'id cannot be nil'
      end

      if id.to_s.length > 25
        fail ArgumentError, 'invalid value for "id", the character length must be smaller than or equal to 25.'
      end

      if id.to_s.length < 1
        fail ArgumentError, 'invalid value for "id", the character length must be great than or equal to 1.'
      end

      @id = id
    end

    # Custom attribute writer method with validation
    # @param [Object] shop_id Value to be assigned
    def shop_id=(shop_id)
      if shop_id.nil?
        fail ArgumentError, 'shop_id cannot be nil'
      end

      if shop_id.to_s.length > 13
        fail ArgumentError, 'invalid value for "shop_id", the character length must be smaller than or equal to 13.'
      end

      if shop_id.to_s.length < 13
        fail ArgumentError, 'invalid value for "shop_id", the character length must be great than or equal to 13.'
      end

      @shop_id = shop_id
    end

    # Custom attribute writer method with validation
    # @param [Object] plan_id Value to be assigned
    def plan_id=(plan_id)
      if plan_id.nil?
        fail ArgumentError, 'plan_id cannot be nil'
      end

      if plan_id.to_s.length > 25
        fail ArgumentError, 'invalid value for "plan_id", the character length must be smaller than or equal to 25.'
      end

      if plan_id.to_s.length < 1
        fail ArgumentError, 'invalid value for "plan_id", the character length must be great than or equal to 1.'
      end

      @plan_id = plan_id
    end

    # Custom attribute writer method with validation
    # @param [Object] plan_name Value to be assigned
    def plan_name=(plan_name)
      if !plan_name.nil? && plan_name.to_s.length > 200
        fail ArgumentError, 'invalid value for "plan_name", the character length must be smaller than or equal to 200.'
      end

      @plan_name = plan_name
    end

    # Custom attribute writer method with validation
    # @param [Object] customer_id Value to be assigned
    def customer_id=(customer_id)
      if customer_id.nil?
        fail ArgumentError, 'customer_id cannot be nil'
      end

      if customer_id.to_s.length > 60
        fail ArgumentError, 'invalid value for "customer_id", the character length must be smaller than or equal to 60.'
      end

      if customer_id.to_s.length < 1
        fail ArgumentError, 'invalid value for "customer_id", the character length must be great than or equal to 1.'
      end

      @customer_id = customer_id
    end

    # Custom attribute writer method with validation
    # @param [Object] card_id Value to be assigned
    def card_id=(card_id)
      if card_id.nil?
        fail ArgumentError, 'card_id cannot be nil'
      end

      if card_id.to_s.length > 25
        fail ArgumentError, 'invalid value for "card_id", the character length must be smaller than or equal to 25.'
      end

      if card_id.to_s.length < 25
        fail ArgumentError, 'invalid value for "card_id", the character length must be great than or equal to 25.'
      end

      @card_id = card_id
    end

    # Custom attribute writer method with validation
    # @param [Object] payment_method_id Value to be assigned
    def payment_method_id=(payment_method_id)
      if payment_method_id.nil?
        fail ArgumentError, 'payment_method_id cannot be nil'
      end

      if payment_method_id.to_s.length > 25
        fail ArgumentError, 'invalid value for "payment_method_id", the character length must be smaller than or equal to 25.'
      end

      if payment_method_id.to_s.length < 25
        fail ArgumentError, 'invalid value for "payment_method_id", the character length must be great than or equal to 25.'
      end

      @payment_method_id = payment_method_id
    end

    # Custom attribute writer method with validation
    # @param [Object] initial_amount Value to be assigned
    def initial_amount=(initial_amount)
      if initial_amount.nil?
        fail ArgumentError, 'initial_amount cannot be nil'
      end

      @initial_amount = initial_amount
    end

    # Custom attribute writer method with validation
    # @param [Object] initial_tax Value to be assigned
    def initial_tax=(initial_tax)
      if initial_tax.nil?
        fail ArgumentError, 'initial_tax cannot be nil'
      end

      @initial_tax = initial_tax
    end

    # Custom attribute writer method with validation
    # @param [Object] initial_total_amount Value to be assigned
    def initial_total_amount=(initial_total_amount)
      if initial_total_amount.nil?
        fail ArgumentError, 'initial_total_amount cannot be nil'
      end

      @initial_total_amount = initial_total_amount
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] end_month_flag Object to be assigned
    def end_month_flag=(end_month_flag)
      validator = EnumAttributeValidator.new('String', ["0", "1"])
      unless validator.valid?(end_month_flag)
        fail ArgumentError, "invalid value for \"end_month_flag\", must be one of #{validator.allowable_values}."
      end
      @end_month_flag = end_month_flag
    end

    # Custom attribute writer method with validation
    # @param [Object] error_code Value to be assigned
    def error_code=(error_code)
      if !error_code.nil? && error_code.to_s.length > 11
        fail ArgumentError, 'invalid value for "error_code", the character length must be smaller than or equal to 11.'
      end

      if !error_code.nil? && error_code.to_s.length < 11
        fail ArgumentError, 'invalid value for "error_code", the character length must be great than or equal to 11.'
      end

      @error_code = error_code
    end

    # Custom attribute writer method with validation
    # @param [Object] client_field_1 Value to be assigned
    def client_field_1=(client_field_1)
      if !client_field_1.nil? && client_field_1.to_s.length > 100
        fail ArgumentError, 'invalid value for "client_field_1", the character length must be smaller than or equal to 100.'
      end

      if !client_field_1.nil? && client_field_1.to_s.length < 1
        fail ArgumentError, 'invalid value for "client_field_1", the character length must be great than or equal to 1.'
      end

      @client_field_1 = client_field_1
    end

    # Custom attribute writer method with validation
    # @param [Object] client_field_2 Value to be assigned
    def client_field_2=(client_field_2)
      if !client_field_2.nil? && client_field_2.to_s.length > 100
        fail ArgumentError, 'invalid value for "client_field_2", the character length must be smaller than or equal to 100.'
      end

      if !client_field_2.nil? && client_field_2.to_s.length < 1
        fail ArgumentError, 'invalid value for "client_field_2", the character length must be great than or equal to 1.'
      end

      @client_field_2 = client_field_2
    end

    # Custom attribute writer method with validation
    # @param [Object] client_field_3 Value to be assigned
    def client_field_3=(client_field_3)
      if !client_field_3.nil? && client_field_3.to_s.length > 100
        fail ArgumentError, 'invalid value for "client_field_3", the character length must be smaller than or equal to 100.'
      end

      if !client_field_3.nil? && client_field_3.to_s.length < 1
        fail ArgumentError, 'invalid value for "client_field_3", the character length must be great than or equal to 1.'
      end

      @client_field_3 = client_field_3
    end

    # Custom attribute writer method with validation
    # @param [Object] remarks Value to be assigned
    def remarks=(remarks)
      if !remarks.nil? && remarks.to_s.length > 9
        fail ArgumentError, 'invalid value for "remarks", the character length must be smaller than or equal to 9.'
      end

      if !remarks.nil? && remarks.to_s.length < 1
        fail ArgumentError, 'invalid value for "remarks", the character length must be great than or equal to 1.'
      end

      @remarks = remarks
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          id == o.id &&
          shop_id == o.shop_id &&
          pay_type == o.pay_type &&
          plan_id == o.plan_id &&
          plan_name == o.plan_name &&
          customer_id == o.customer_id &&
          card_id == o.card_id &&
          payment_method_id == o.payment_method_id &&
          amount == o.amount &&
          tax == o.tax &&
          total_amount == o.total_amount &&
          initial_amount == o.initial_amount &&
          initial_tax == o.initial_tax &&
          initial_total_amount == o.initial_total_amount &&
          status == o.status &&
          start_date == o.start_date &&
          next_charge_date == o.next_charge_date &&
          stop_date == o.stop_date &&
          end_month_flag == o.end_month_flag &&
          send_url == o.send_url &&
          error_code == o.error_code &&
          client_field_1 == o.client_field_1 &&
          client_field_2 == o.client_field_2 &&
          client_field_3 == o.client_field_3 &&
          remarks == o.remarks &&
          created == o.created &&
          updated == o.updated
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [id, shop_id, pay_type, plan_id, plan_name, customer_id, card_id, payment_method_id, amount, tax, total_amount, initial_amount, initial_tax, initial_total_amount, status, start_date, next_charge_date, stop_date, end_month_flag, send_url, error_code, client_field_1, client_field_2, client_field_3, remarks, created, updated].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def self._deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = FincodeApiClient.const_get(type)
        klass.respond_to?(:openapi_any_of) || klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
