=begin
#fincode API

#fincodeのAPIリファレンスです。\\ fincodeは決済情報のほか様々なリソースを管理できるため、リソース指向なREST APIをベースとしたインターフェイス設計のもとでAPIを提供しています。\\ APIの呼び出しにはAPIキーによる認証が必要であり、リクエストの際に`Authorization`ヘッダーに有効なAPIキーをセットすることで認証できます。 

The version of the OpenAPI document: 1.4.0

Generated by: https://openapi-generator.tech
Generator version: 7.19.0

=end

require 'date'
require 'time'

module FincodeApiClient
  class ThreeDSecureAuthorizingResponse < ApiModelBase
    attr_accessor :tds2_trans_result

    attr_accessor :tds2_trans_result_reason

    # 決済種別   この決済で利用する決済手段です。未指定の場合、`Card`となります。  - `Card`: カード（デフォルト） - `Googlepay`: Google Pay 
    attr_accessor :pay_type

    # 3Dセキュア2.0認証チャレンジURL\\ \\ 購入者による`acs_url`へのアクセス後、カード発行会社によって追加のチャレンジ認証が必要と判定された場合、このパラメータにURLが設定されて返却されます。 
    attr_accessor :challenge_url

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'tds2_trans_result' => :'tds2_trans_result',
        :'tds2_trans_result_reason' => :'tds2_trans_result_reason',
        :'pay_type' => :'pay_type',
        :'challenge_url' => :'challenge_url'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'tds2_trans_result' => :'ThreeDSecure2TransactionResult',
        :'tds2_trans_result_reason' => :'ThreeDSecure2TransactionResultReason',
        :'pay_type' => :'String',
        :'challenge_url' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'challenge_url'
      ])
    end

    # List of class defined in allOf (OpenAPI v3)
    def self.openapi_all_of
      [
      :'ThreeDSecureTransResult'
      ]
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `FincodeApiClient::ThreeDSecureAuthorizingResponse` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `FincodeApiClient::ThreeDSecureAuthorizingResponse`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'tds2_trans_result')
        self.tds2_trans_result = attributes[:'tds2_trans_result']
      end

      if attributes.key?(:'tds2_trans_result_reason')
        self.tds2_trans_result_reason = attributes[:'tds2_trans_result_reason']
      end

      if attributes.key?(:'pay_type')
        self.pay_type = attributes[:'pay_type']
      else
        self.pay_type = 'Card'
      end

      if attributes.key?(:'challenge_url')
        self.challenge_url = attributes[:'challenge_url']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if !@challenge_url.nil? && @challenge_url.to_s.length > 256
        invalid_properties.push('invalid value for "challenge_url", the character length must be smaller than or equal to 256.')
      end

      if !@challenge_url.nil? && @challenge_url.to_s.length < 1
        invalid_properties.push('invalid value for "challenge_url", the character length must be greater than or equal to 1.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      pay_type_validator = EnumAttributeValidator.new('String', ["Card", "Googlepay"])
      return false unless pay_type_validator.valid?(@pay_type)
      return false if !@challenge_url.nil? && @challenge_url.to_s.length > 256
      return false if !@challenge_url.nil? && @challenge_url.to_s.length < 1
      true
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] pay_type Object to be assigned
    def pay_type=(pay_type)
      validator = EnumAttributeValidator.new('String', ["Card", "Googlepay"])
      unless validator.valid?(pay_type)
        fail ArgumentError, "invalid value for \"pay_type\", must be one of #{validator.allowable_values}."
      end
      @pay_type = pay_type
    end

    # Custom attribute writer method with validation
    # @param [Object] challenge_url Value to be assigned
    def challenge_url=(challenge_url)
      if !challenge_url.nil? && challenge_url.to_s.length > 256
        fail ArgumentError, 'invalid value for "challenge_url", the character length must be smaller than or equal to 256.'
      end

      if !challenge_url.nil? && challenge_url.to_s.length < 1
        fail ArgumentError, 'invalid value for "challenge_url", the character length must be greater than or equal to 1.'
      end

      @challenge_url = challenge_url
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          tds2_trans_result == o.tds2_trans_result &&
          tds2_trans_result_reason == o.tds2_trans_result_reason &&
          pay_type == o.pay_type &&
          challenge_url == o.challenge_url
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [tds2_trans_result, tds2_trans_result_reason, pay_type, challenge_url].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
